admittance_params:
  # Simulation
  #mass: [1.0, 1.0, 1.0, 1.0]
  #damping: [100.0, 100.0, 100.0, 100.0]
  #stiffness: [10.0, 10.0, 10.0, 10.0]

  # Real
  # mass: [100.0, 100.0, 10.0, 10.0]
  # damping: [447.0, 447.0, 44.7, 44.7]
  # stiffness: [500.0, 500.0, 50.0, 50.0]
  # Sensibilidad aumentada
  # mass: [50.0, 100.0, 5.0, 5.0]
  # damping: [223.5, 447.0, 22.35, 22.35]
  ##NORMAL##
  # stiffness: [250.0, 500.0, 25.0, 25.0]
  # mass: [200.0, 200.0, 20.0, 20.0]
  # damping: [894.0, 894.0, 89.4, 89.4]
  
  #AJUSTE PRUEBA PAU
  #NO RETURN AT ORIGINAL PATH
  # Constantes pie (torsion imposible)
  # stiffness: [0.0, 0.0, 0.0, 0.0]
  # mass: [200.0, 400.0, 15.0, 500.0] #5.0]
  # damping: [894.0, 1788.0, 67.05, 2235.0] #22.35]
  # Constantes mano (torsion imposible)
  stiffness: [0.0, 0.0, 0.0, 0.0]
  mass: [100.0, 300.0, 7.5, 500.0] #5.0]
  damping: [447.0, 1341.0, 33.52, 2235.0] #22.35]
  #mass: [2000.0, 4000.0, 7.5, 500.0]
  #damping: [8940.0, 17880.0, 33.5, 2235.0]

# Activation the calibration of the force sensor
calibration: true
# Keep the noise_threshold in false if the boot compensation is used
noise_threshold: true

# For boot compensation and fixed frame
boot_compensation: false
fixed_frame_noise_threshold: false
boot_mass: 2.2816
boot_cdg: [0.1201, 0.0007, 0.0453]

#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/admittance/ref_Fent_TE0_CF1_5P_V1.txt"
#PAU free
ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayIniFuerza.txt"
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayFuerza_MVC1.txt"
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/EstaticoFuerzas.txt"

# admittance/ref_Fent_TE0_CF1_VF1_z_2.txt"

# data['force']
# Has exact copy. Maybe it will be better to include the robot_name option