admittance_params:
  # Simulation
  #mass: [1.0, 1.0, 1.0, 1.0]
  #damping: [100.0, 100.0, 100.0, 100.0]
  #stiffness: [10.0, 10.0, 10.0, 10.0]

  # Real
  # mass: [100.0, 100.0, 10.0, 10.0]
  # damping: [447.0, 447.0, 44.7, 44.7]
  # stiffness: [500.0, 500.0, 50.0, 50.0]
  # Sensibilidad aumentada
  # mass: [50.0, 100.0, 5.0, 500.0]
  # damping: [223.5, 447.0, 22.35, 2235.0]
  ##NORMAL##
  # stiffness: [250.0, 500.0, 25.0, 25.0]
  # mass: [600.0, 600.0, 60.0, 500.0]
  # damping: [2700.0, 2700.0, 270.0, 2235.0]

    ##NO ROTATIONSL##
  #stiffness: [0.0, 0.0, 0.0, 0.0]
  #mass: [600.0, 600.0, 500.0, 500.0]
  #damping: [2700.0, 2700.0, 2235.0, 2235.0]

  #mass: [600.0, 600.0, 30.0, 500.0]
  #damping: [1800.0, 1800.0, 90.0, 2235.0]

  # Sensibilidad aumentada
  #mass: [50.0, 100.0, 5.0, 5.0]
  #damping: [223.5, 447.0, 22.35, 22.35]

  #AJUSTE PRUEBA PAU
  #NO RETURN AT ORIGINAL PATH
  # Constantes pie (torsion imposible)
  # stiffness: [0.0, 0.0, 0.0, 0.0]
  # mass: [200.0, 400.0, 15.0, 500.0] #5.0]
  # damping: [894.0, 1788.0, 67.05, 2235.0] #22.35]
  # Constantes mano (torsion imposible)
  stiffness: [0.0, 0.0, 0.0, 0.0]
  mass: [200.0, 200.0, 5.0, 1000.0] #5.0]
  damping: [894.0, 894.0, 22.35, 4470.0] #22.35]


  # Parametros fisios
    #stiffness: [0.0, 0.0, 0.0, 0.0]
    #mass: [100.0, 300.0, 7.5, 500.0] #7.5, 5.0]
    #damping: [447.0, 1341.0, 33.52, 2235.0] #33.52, 22.35]
  #mass: [2000.0, 4000.0, 7.5, 500.0]
  #damping: [8940.0, 17880.0, 33.5, 2235.0]

# Activation the calibration of the force sensor
calibration: true
# Keep the noise_threshold in false if the boot compensation is used
noise_threshold: true

# For boot compensation and fixed frame
boot_compensation: false
fixed_frame_noise_threshold: false
boot_mass: 2.2816
boot_cdg: [0.1201, 0.0007, 0.0453]

# ENVELOPE TEST ------- PAU
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Envelope/TrayFuerzas_MVC_2.txt"

#########################
# FORCE TRACKING ------- PAU
# ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Carles_20230720/TrayFuerzSegFuerza_Carles0720_mus_8.txt"


#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/admittance/ref_Fent_TE0_CF1_5P_V1.txt"
#PAU free
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayIniFuerza.txt"
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayFuerza_MVC1.txt"
# ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/EstaticoFuerzas.txt"
# ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayFuerza_Cal_JL_1.txt"
# ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230601/FuerzaSegFuerza.txt"
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayFuerzas_Estatica_Jose.txt"
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230629/TrayFuerza_Estatica.txt"
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayFuerzSegFuerzaRod_Angel2706_mus_15.txt"
#ref_force_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230726/TrayFuerzas_Estatica_Angel.txt"

#################
# TRAYECTORIAS PROPIOCEPCION
ref_force_path: "/home/paralelo4dofnew/SharedFolder/Propiocepcion Trayectorias/Test2/EstaticoFuerzas.txt"

#################
# TRAYECTORIAS FEM
#ref_force_path: "/home/paralelo4dofnew/SharedFolder/FEE-Trayectorias/Marina/TrayFuerzSegFuerza_mus_14-5.txt"

# admittance/ref_Fent_TE0_CF1_VF1_z_2.txt"

# data['force']
# Has exact copy. Maybe it will be better to include the robot_name option