# No se usa por el momento
ts: 0.01

robot:
  robot_name: 'robot_5p' #'robot_3ups_rpu' #'robot_5p'
  config: 1
  v_sat: 5.0

robot_3ups_rpu: 
  encoder_gearbox: [1.0, 1.0, 1.0, 0.230769230769231]
  ref_path:
    q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/singular/ref_qinde_TRR8_CF1_VS1.txt" #ref_qinde_TRR15_CF1_VS1.txt" #admittance/ref_qinde_TE0_CF1_VF1.txt"
    x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/singular/ref_cart_TRR8_CF1_VS1.txt" #ref_cart_TRR15_CF1_VS1.txt" #admittance/ref_cart_TE0_CF1_VF1.txt"


robot_5p:
  encoder_gearbox: [0.230769230769231, 0.230769230769231, 0.230769230769231, 0.230769230769231]
  ref_path:

    #PAUMID
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/PauMid/ref_qinde_TRRPauMid_CF1_5P_V1.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/PauMid/ref_cart_TRRPauMid_CF1_5P_V1.txt"
    
    #Static trajectory for force control in the new robot
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/PauFree/ref_qinde_TE0Pau_CF1_5P_V1.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/PauFree/ref_cart_TE0Pau_CF1_5P_V1.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_qinde_TRRDEMO_CF1_5P_V1.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_cart_TRRDEMO_CF1_5P_V1.txt"
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/admittance/ref_qinde_TE0_CF1_5P_V1.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/admittance/ref_cart_TE0_CF1_5P_V1.txt"

    # GMR
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_qinde_gmr_rev.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_cart_gmr_rev.txt"

    # References Fisio

    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayIniPatas.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayIniCart.txt"

    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayPatas_MVC1.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayCart_MVC1.txt"


    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayPatas.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayCart.txt"
   
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/EstaticoPatas.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/EstaticoCart.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayPatas_Cal_JL_1.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayCart_Cal_JL_1.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_Test/JoseTest2_StaticPatas.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_Test/JoseTest2_StaticCart.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230601/PatasSegFuerza.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230601/TrayectoriaSegFuerza.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayPatas_Mus12_Jose_long.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayCarte_Mus12_Jose_long.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayPatas_Mus12_Estatica_Jose.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayCarte_Mus12_Estatica_Jose.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayPatasVal.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayCartVal.txt"

    #########################
    # ENVELOPE TEST ------- PAU
    
    #MVC1
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references//bio/Envelope/TrayPatas_MVC_2.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Envelope/TrayCart_MVC_2.txt"


    #########################
    # FORCE TRACKING ------- PAU
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references//bio/Elena_20230713/TrayPatasValC.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Elena_20230713/TrayCartValC.txt"

    #################
    # JOSE 20230717
    q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230717/TrayPatas_mus7_Jose_Estatica.txt"
    x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230717/TrayCarte_mus7_Jose_Estatica.txt"


    


#PARA PRUEBA DE PAU CON ANGEL 20230627

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230629/TrayPatas_MVC_2.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230629/TrayCart_MVC_2.txt"

    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayPatas_mus7_Jose_Estatica.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayCarte_mus7_Jose_Estatica.txt"
#PRUEBA PARA MOVIMIENTO DEL ROBOT Y REFERENCIA DE FUERZA
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayPatasSegFuerzaRod_Angel2706_mus_15.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayCartSegFuerzaRod_Angel2706_mus_15.txt"

    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230706/TrayPatas_mus7_Jose_Estatica.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230706/TrayCarte_mus7_Jose_Estatica.txt"


#Iterations for direct kinematics
dir_kin:
  tol: 0.0000001
  iter: 30

# Use of displayer
displayer:
  data_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/pauses/ind_pause_TRR8_CF1_IDHolgV1_ext.txt"

# Lenghts of tibia and foot
patient_data:
  length_tibia: 0.3960
  length_foot: 0.1182

# data['general']
# Includes all this data and also init_q and init_x