# No se usa por el momento
ts: 0.01

# Number of samples set for executing
Nptos_set: 0  # If it is <= 0 the number of sample is taken from the ref txt file

robot:
  robot_name: 'robot_5p' #'robot_3ups_rpu' #'robot_5p'
  config: 1
  v_sat: 5.0

robot_3ups_rpu: 
  encoder_gearbox: [1.0, 1.0, 1.0, 0.230769230769231]
  ref_path:
    q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/singular/ref_qinde_TRR8_CF1_VS1.txt" #ref_qinde_TRR15_CF1_VS1.txt" #admittance/ref_qinde_TE0_CF1_VF1.txt"
    x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/singular/ref_cart_TRR8_CF1_VS1.txt" #ref_cart_TRR15_CF1_VS1.txt" #admittance/ref_cart_TE0_CF1_VF1.txt"


robot_5p:
  encoder_gearbox: [0.230769230769231, 0.230769230769231, 0.230769230769231, 0.230769230769231]
  ref_path:

    #PAUMID
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/PauMid/ref_qinde_TRRPauMid_CF1_5P_V1.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/PauMid/ref_cart_TRRPauMid_CF1_5P_V1.txt"
    
    #Static trajectory for force control in the new robot
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/PauFree/ref_qinde_TE0Pau_CF1_5P_V1.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/PauFree/ref_cart_TE0Pau_CF1_5P_V1.txt"

    #DEMOSTRATION ANGEL
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_qinde_TRRDEMO_CF1_5P_V1.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_cart_TRRDEMO_CF1_5P_V1.txt"
    
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/admittance/ref_qinde_TE0_CF1_5P_V1.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/admittance/ref_cart_TE0_CF1_5P_V1.txt"

    # GMR
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_qinde_gmr_rev.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_cart_gmr_rev.txt"

    # References Fisio

    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayIniPatas.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayIniCart.txt"

    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayPatas_MVC1.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayCart_MVC1.txt"


    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayPatas.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayCart.txt"
   
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/EstaticoPatas.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/EstaticoCart.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayPatas_Cal_JL_1.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Fisio/TrayCart_Cal_JL_1.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_Test/JoseTest2_StaticPatas.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_Test/JoseTest2_StaticCart.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230601/PatasSegFuerza.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230601/TrayectoriaSegFuerza.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayPatas_Mus12_Jose_long.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayCarte_Mus12_Jose_long.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayPatas_Mus12_Estatica_Jose.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayCarte_Mus12_Estatica_Jose.txt"

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayPatasVal.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayCartVal.txt"

    #########################
    # ENVELOPE TEST ------- PAU
    
    #MVC1
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references//bio/Envelope/TrayPatas_MVC_2.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Envelope/TrayCart_MVC_2.txt"


    #########################
    # FORCE TRACKING ------- PAU
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230726/TrayPatas_mus1_Angel_Estatica.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230726/TrayCarte_mus1_Angel_Estatica.txt"


    #################
    # JOSE 20230717
    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230717/TrayPatas_mus7_Jose_Estatica.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230717/TrayCarte_mus7_Jose_Estatica.txt"

    ##################
    # TRAYECTORIAS PROPIOCEPCION
    # q: "/home/paralelo4dofnew/SharedFolder/Propiocepcion Trayectorias/Variable femur/ref_qinde_TRPPC_CF1_I90_T53_L0.49.txt"
    # x: "/home/paralelo4dofnew/SharedFolder/Propiocepcion Trayectorias/Variable femur/ref_cart_TRPPC_CF1_I90_T53_L0.49.txt"

    ##################
    # TRAYECTORIAS ADAPTIVE LAW WITH NEURAL NETWORK 
    q: "/home/paralelo4dofnew/SharedFolder/Trayectorias/Lotfy/ref_qinde_TRR17_CF1_5P_IdV1.txt"
    x: "/home/paralelo4dofnew/SharedFolder/Trayectorias/Lotfy/ref_cart_TRR17_CF1_5P_IdV1.txt"

    #COMPENSACIONES
    # PAu L0.47 T53 T30
    # Angel L0.5 T53 T36   % NO ES 56
    # Eugenio L0.44 T53 T33
    # Marina L0.44 T56  !!!!!OJO CAMBIA PUNTO DE INICIO (Z+4cm) Y NOMBRE a TRPPC_mar
    # Elena L0.48 T54
    # Amparo L0.43 T50 T33    USO: TRPPC_mar
    # Marta L0.44 T33         USO: TRPPC_mar
    # Noemi L0.45 T50 T30     USO: TRPPC_mar
    # Sara L0.43 T33 T53      USO: TRPPC_mar 
    # Ferran L0.51 T33 T50   
    # Mario L0.48 T30 T50
    # Ana L0.49 T33 T53
    # Maria L0.45 T36 T50     USO: TRPPC_mar
    # Laura L0.49 T33 T53

    #!!!!!!!!!!!! las trayectorias suavisadas tienen una "S" al final de la TRPPC "S" !!!!!!!!!!!!


    #################
    # TRAYECTORIAS FEM
    #q: "/home/paralelo4dofnew/SharedFolder/FEE-Trayectorias/Marina/TrayPatasSegFuerza_mus_14.txt"
    #x: "/home/paralelo4dofnew/SharedFolder/FEE-Trayectorias/Marina/TrayCartSegFuerza_mus_14.txt"

    #Trayectorias Iniciales
    # q: "/home/paralelo4dofnew/SharedFolder/FEE-Trayectorias/00-Trayectorias iniciales/02_Vastos_Patas_CF1.txt"
    # x: "/home/paralelo4dofnew/SharedFolder/FEE-Trayectorias/00-Trayectorias iniciales/02_Vastos_Cartesianas_CF1.txt"

    # POINT GENERATED FROM MATLAB TO START IN THE ACTUAL POSE
    #q: "/home/paralelo4dofnew/SharedFolder/ref_qinde_TRRBio_CF1_V1.txt"
    #x: "/home/paralelo4dofnew/SharedFolder/ref_cart_TRRBio_CF1_V1.txt"
    


#PARA PRUEBA DE PAU CON ANGEL 20230627

    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230629/TrayPatas_MVC_2.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230629/TrayCart_MVC_2.txt"

    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayPatas_mus7_Jose_Estatica.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230621/TrayCarte_mus7_Jose_Estatica.txt"
#PRUEBA PARA MOVIMIENTO DEL ROBOT Y REFERENCIA DE FUERZA
    # q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayPatasSegFuerzaRod_Angel2706_mus_15.txt"
    # x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Angel_20230627/TrayCartSegFuerzaRod_Angel2706_mus_15.txt"

    #q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230706/TrayPatas_mus7_Jose_Estatica.txt"
    #x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/bio/Jose_20230706/TrayCarte_mus7_Jose_Estatica.txt"


#Iterations for direct kinematics
dir_kin:
  tol: 0.0000001
  iter: 30

# Use of displayer
displayer:
  data_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/pauses/ind_pause_TRR8_CF1_IDHolgV1_ext.txt"

# Lenghts of tibia and foot
patient_data:
  length_tibia: 0.3960
  length_foot: 0.1182

# data['general']
# Includes all this data and also init_q and init_x