# No se usa por el momento
ts: 0.01

robot:
  robot_name: 'robot_5p' #'robot_3ups_rpu' #'robot_5p'
  config: 1
  v_sat: 9.5

robot_3ups_rpu: 
  encoder_gearbox: [1.0, 1.0, 1.0, 1.0]
  ref_path:
    q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/singular/ref_qinde_TE0_CF1_VFS1.txt" #ref_qinde_TRR15_CF1_VS1.txt" #admittance/ref_qinde_TE0_CF1_VF1.txt"
    x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/singular/ref_cart_TE0_CF1_VFS1.txt" #ref_cart_TRR15_CF1_VS1.txt" #admittance/ref_cart_TE0_CF1_VF1.txt"

robot_5p:
  encoder_gearbox: [0.23077, 0.23077, 0.23077, 1.0]
  ref_path:
    q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_qinde_TRVAL1_CF1_5P_V1.txt"
    x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_cart_TRVAL1_CF1_5P_V1.txt"

#Iterations for direct kinematics
dir_kin:
  tol: 0.0000001
  iter: 30

# Use of displayer
displayer:
  data_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/pauses/ind_pause_TRR8_CF1_IDHolgV1_ext.txt"

# data['general']
# Includes all this data and also init_q and init_x