robot_3ups_rpu:
  vp_conversion:  [1.0, 1.0, 1.0, 1.0]
  controller:
    k1: 0.75
    k2: 0.5

robot_5p:
  vp_conversion:  [4.333333, 4.333333, 4.33333, 1.0]
  controller:
    k1: 0.75
    k2: 0.5

# data['gus']
# Includes only the data of the robot in hand
# Exact copy