pd:
  #kp: [10000.0, 10000.0, 10000.0, 50000.0]
  #kp: [5000.0, 5000.0, 5000.0, 20000.0]
  kp: [5000.0, 5000.0, 5000.0, 50000.0]
  #kp: [2000.0, 2000.0, 2000.0, 50000.0]
  #kd: [100.0, 100.0, 100.0, 500.0]
  #kd: [500.0, 500.0, 500.0, 2500.0]
  kd: [50.0, 50.0, 50.0, 2500.0]
  #kd: [100.0, 100.0, 100.0, 2500.0]
  #kd: [25.0, 25.0, 25.0, 2500.0]
# Si se usa el de Gus habra que cambiar las ganancias por las constantes de volt a F

# Deben elegirse los nombres para que quede claro a qué referencia se refiere.
# NO poner txt
load_path: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/ilc_data/ref_TRR3_CF1_IdV1_mod_kp3kd3_10PID_4"
save_path: ""
# Hay que escribir a mano la repeticion de la trayectoria
traj_repetitions: 9.0

# data['ilc']
# Exact copy