ts: 0.01

robot: 
  robot_name: 'robot_3ups_rpu'
  config: 1

actuators:
  v_sat: 9.5
  vp_conversion: [1.0, 1.0, 1.0, 1.0] #[4.333333, 4.333333, 4.33333, 1.0]

controller:
  k1: 0.75
  k2: 0.5

ref_path:
  q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_qinde_TRR3_CF1_5P_IdV1.txt"
  x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/ref_5p/ref_cart_TRR3_CF1_5P_IdV1.txt"