ts: 0.01

robot: 
  robot_name: 'robot_5p'
  config: 1

actuators:
  v_sat: 9.5
  vp_conversion: [1.0, 1.0, 1.0, 1.0]

controller:
  k1: 0.75
  k2: 0.5

ref_path: "/home/paralelo4dofnew/ros2_eloquent_ws/parallel_robot/references/ref_qinde_TRR17_CF1_5P_IdV1.txt"