ts: 0.01

robot: 
  robot_name: "robot_3ups_rpu"
  config: 1

actuators:
  v_sat: 9.5
  vp_conversion: [28.4628, 28.4628, 28.4628, 246.6779]

controller:
  #PDG
  kp: [27394.2003, 27394.2003, 27394.2003, 255168.2203]
  kv: [109.7532, 109.7532, 109.7532, 17927.4511]
  #PID
  ki: [1000.0, 1000.0, 2000.0, 10000.0]

ref_path:
  q: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/refeprism_indep_TRR8.txt"
  x: "/home/paralelo4dofnew/ros2_eloquent_ws/pr_4dof/references/refecart_TRR8_identificar.txt"

#For PDG
dir_kin:
  tol: 0.0000001
  iter: 30