ts: 0.01

robot: 
  robot_name: "robot_5p"
  config: 1

actuators:
  v_sat: 9.5
  vp_conversion: [28.4628, 28.4628, 28.4628, 246.6779]

controller:
  kp: [27394.2003, 27394.2003, 27394.2003, 255168.2203]
  kv: [109.7532, 109.7532, 109.7532, 17927.4511]

ref_path:
  q: "/home/paralelo4dofnew/ros2_eloquent_ws/parallel_robot/references/ref_qinde_TRR3_CF1_5P_IdV1.txt"
  x: "/home/paralelo4dofnew/ros2_eloquent_ws/parallel_robot/references/ref_cart_TRR3_CF1_5P_IdV1.txt"

dir_kin:
  tol: 0.0000001
  iter: 30